"""One-shot strings + grep scan of CrimsonDesert.exe for characterinfo schema hints."""
from __future__ import annotations
import re
import sys
from pathlib import Path

EXE = Path(r"C:\Program Files (x86)\Steam\steamapps\common\Crimson Desert\bin64\CrimsonDesert.exe")
OUT = Path(r"C:\Users\hzeem\Desktop\crimsonforge\tools\schema_hints.txt")

# Patterns we care about (case-insensitive search later)
KEYWORDS = [
    # Direct table refs
    r"characterinfo",
    r"CharacterInfo",
    # UE-style class prefixes
    r"\bF[A-Z][A-Za-z0-9_]*Row\b",
    r"\bF[A-Z][A-Za-z0-9_]*Stat\b",
    r"\bF[A-Z][A-Za-z0-9_]*Info\b",
    r"\bU[A-Z][A-Za-z0-9_]*Character[A-Za-z0-9_]*\b",
    r"\bF[A-Z][A-Za-z0-9_]*Character[A-Za-z0-9_]*\b",
    # PA-style table names
    r"\.pabgb",
    r"\.pasrc",
    # Stat-ish field names — common across MMOs/RPGs
    r"\bMaxHP\b",
    r"\bMaxHp\b",
    r"\bAttack(Range|Power|Speed|Damage)?\b",
    r"\bAggroRange\b",
    r"\bMoveSpeed\b",
    r"\bDefense\b",
    r"\bDefence\b",
    r"\bBoneScaleBuffer\b",
    r"\bMorphTargetSet\b",
    r"\bBodyScale\b",
    r"\bBoneScale\b",
    r"\bSightRange\b",
    r"\bHearingRange\b",
    r"\bWeaponType\b",
    # The actual key
    r"Boss_Ogre_55515",
    r"55515",
    # Misc PA naming
    r"\bCharStat\b",
    r"\bBossInfo\b",
    r"\bMonsterInfo\b",
    r"\bNpcInfo\b",
    r"\bPrefab\b",
    r"\bLayout\b",
    # Common character keys to find context
    r"CD_M\d{4}_\d{2}_[A-Za-z]+",
    # AssetReference-style fields
    r"\b[A-Z][A-Za-z0-9_]*Path\b",
    r"\b[A-Z][A-Za-z0-9_]*AssetRef\b",
    # Any string containing characterinfo. (member access)
    r"characterinfo\.[A-Za-z_]+",
    r"CharacterInfo\.[A-Za-z_]+",
]

# Build a single combined regex with named groups for each pattern.
combined = re.compile(
    rb"|".join(p.encode("ascii") for p in KEYWORDS),
    re.IGNORECASE,
)

# Also extract printable ASCII runs >= 6 chars so we can look at neighbors.
# Limit to runs <= 200 chars to avoid pulling in noise.
ascii_run = re.compile(rb"[\x20-\x7e]{6,200}")

def scan() -> dict:
    print(f"Reading {EXE} ({EXE.stat().st_size / 1024 / 1024:.1f} MB)")
    data = EXE.read_bytes()
    print("Scanning ASCII runs ...")

    runs = ascii_run.findall(data)
    print(f"  total runs: {len(runs):,}")

    # Decode and dedupe
    seen: set[str] = set()
    decoded: list[str] = []
    for r in runs:
        try:
            s = r.decode("ascii")
        except UnicodeDecodeError:
            continue
        if s not in seen:
            seen.add(s)
            decoded.append(s)
    print(f"  unique runs: {len(decoded):,}")

    # Bucket hits by pattern
    hits: dict[str, list[str]] = {}
    boss_hit = False
    for s in decoded:
        # A combined search for any of the keywords:
        sl = s.encode("ascii", errors="ignore")
        for pat in KEYWORDS:
            try:
                if re.search(pat, s, re.IGNORECASE):
                    hits.setdefault(pat, []).append(s)
                    if "55515" in s and "ogre" in s.lower():
                        boss_hit = True
                    break  # only bucket each string once
            except re.error:
                pass

    return {"hits": hits, "boss_hit": boss_hit, "total_runs": len(decoded)}


def main() -> int:
    if not EXE.exists():
        print(f"EXE not found at {EXE}", file=sys.stderr)
        return 1
    result = scan()
    hits = result["hits"]

    # Collect all hit strings to also dump a flat list of unique field names
    # Look for short identifier-like strings that resemble field names:
    # CamelCase / snake_case, length 4..40
    field_re = re.compile(r"^[A-Z][A-Za-z0-9_]{3,40}$")
    flat: set[str] = set()
    for strings in hits.values():
        for s in strings:
            for tok in re.findall(r"[A-Za-z_][A-Za-z0-9_]+", s):
                if field_re.match(tok) and len(tok) >= 4:
                    flat.add(tok)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as fh:
        fh.write("# Crimson Desert characterinfo.pabgb schema hints\n")
        fh.write(f"# Generated by tools/scan_exe_schema.py\n")
        fh.write(f"# EXE: {EXE}\n")
        fh.write(f"# Total unique ASCII runs scanned: {result['total_runs']:,}\n")
        fh.write(f"# Boss_Ogre_55515 found in EXE: {result['boss_hit']}\n\n")

        fh.write("=" * 70 + "\n")
        fh.write("SECTION 1 — EXE string hits, bucketed by pattern\n")
        fh.write("=" * 70 + "\n\n")
        for pat, strings in sorted(hits.items(), key=lambda kv: -len(kv[1])):
            fh.write(f"## Pattern: {pat}  ({len(strings)} hits)\n")
            # Cap each bucket at 200 lines to keep file manageable
            for s in strings[:200]:
                fh.write(f"  {s}\n")
            if len(strings) > 200:
                fh.write(f"  ... ({len(strings) - 200} more)\n")
            fh.write("\n")

        fh.write("\n" + "=" * 70 + "\n")
        fh.write("SECTION 2 — flat list of likely field-name identifiers\n")
        fh.write(f"           ({len(flat)} unique CamelCase tokens, len >= 4)\n")
        fh.write("=" * 70 + "\n\n")
        for tok in sorted(flat):
            fh.write(tok + "\n")

    print(f"Wrote {OUT}")
    print(f"Boss_Ogre_55515 found: {result['boss_hit']}")
    print(f"Total bucket categories with hits: {len(hits)}")
    print(f"Total unique CamelCase candidate tokens: {len(flat)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
